### ISSUE TITLE
beets backend json/utf8 errors

### ISSUE THREAD

**Issue by reconmaster** [mopidy/mopidy-beets#22]
I have been having multiple errors when attempting to use mopidy to browse my beets library. I'm not sure what is causing the json error, but I've even added the nginx proxy in case that may have something to do with it. I don't use %asciify names when using beets as I have a large collection of japanese and russian albums that really need UTF-8. I only meniton that in case it sheds light on the issue.

**json error**
```
INFO     Beets - invalid sorting field ignore: albumartist
ERROR    BeetsBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python2.7/site-packages/pykka/future.py", line 299, in get
    exec('raise exc_info[0], exc_info[1], exc_info[2]')
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/site-packages/mopidy_beets/library.py", line 61, in browse
    ['track+'])
  File "/usr/lib/python2.7/site-packages/mopidy_beets/client.py", line 49, in _memoized
    return self.func(*args)
  File "/usr/lib/python2.7/site-packages/mopidy_beets/client.py", line 93, in get_tracks_by
    exact_text, sort_fields)
  File "/usr/lib/python2.7/site-packages/mopidy_beets/client.py", line 162, in _get_objects_by_attribute
    items = self._get(query_url)['results']
  File "/usr/lib/python2.7/site-packages/mopidy_beets/client.py", line 259, in _get
    return req.json()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 858, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python2.7/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value or ']': line 1 column 13 (char 12)
```

**UTF-8**
```
ERROR    BeetsBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python2.7/site-packages/pykka/future.py", line 299, in get
    exec('raise exc_info[0], exc_info[1], exc_info[2]')
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/site-packages/mopidy_beets/library.py", line 72, in browse
    return browser.get_directory(item_id)
  File "/usr/lib/python2.7/site-packages/mopidy_beets/browsers/albums.py", line 20, in get_directory
    self.sort_fields)
  File "/usr/lib/python2.7/site-packages/mopidy_beets/client.py", line 49, in _memoized
    return self.func(*args)
  File "/usr/lib/python2.7/site-packages/mopidy_beets/client.py", line 99, in get_albums_by
    exact_text, sort_fields)
  File "/usr/lib/python2.7/site-packages/mopidy_beets/client.py", line 149, in _get_objects_by_attribute
    value = quote_and_encode(attribute[1])
  File "/usr/lib/python2.7/site-packages/mopidy_beets/client.py", line 135, in quote_and_encode
    text = text.replace(':', r'\:')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
```

**Comment by apiontek** [comment]
I am also experiencing these errors, and have files with UTF-8 characters.

**Comment by jodal** [comment]
The pre-release Mopidy-Beets 4.0.0rc1, compatible with Mopidy 3 and Python 3.7+, is now on PyPI. You can test it out by installing with `python3 -m pip install --pre Mopidy-Beets`.

As the change from Python 2.7 to 3 changes a lot regarding encoding, I'm closing this issue on the assumption that this is no longer a problem. Please open a new issue if you experience encoding issues on Mopidy 3 / Python 3.7+.
